apiVersion: v1
kind: Service
metadata:
  name: php-simple-register-app
  namespace: test-app
  labels:
    app: php-simple-register-app
    app.kubernetes.io/name: php-simple-register-app
    app.kubernetes.io/instance: php-simple-register-app
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app: php-simple-register-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 8443
      targetPort: 8443
      protocol: TCP
