apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: php-app-register
  namespace: openshift-gitops
spec:
  destination:
    namespace: test-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/php-simple-register
    repoURL: https://github.com/Olad03/test-app-gitops
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
